name: Merge release branch to main
on:
  push:
    branches:
      - 'release/*'

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Merge to main
        uses: devmasx/merge-branch@v1.1.0
        with:
          type: now
          target_branch: 'main'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
